const IMG='https://image.tmdb.org/t/p/w500';
const RAW='https://raw.githubusercontent.com';
let state={series:[],settings:{}};
const $=q=>document.querySelector(q);
function toast(t){let d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2800)}
function saveSettings(s){localStorage.setItem('bidamax_admin_settings',JSON.stringify(s));state.settings=s}
function loadSettings(){try{state.settings=JSON.parse(localStorage.getItem('bidamax_admin_settings')||'{}')}catch(e){state.settings={}}}
function encPath(p){return p.split('/').map(encodeURIComponent).join('/')}
function githubHeaders(){return {Authorization:'token '+state.settings.token,Accept:'application/vnd.github+json','Content-Type':'application/json'}}
function ghApi(path){return `https://api.github.com/repos/${state.settings.owner}/${state.settings.repo}/contents/${encPath(path)}`}
async function ghGet(path){let r=await fetch(ghApi(path),{headers:githubHeaders()});if(r.status===404)return null;if(!r.ok)throw new Error(await r.text());return await r.json()}
async function ghGetJson(path,def){let f=await ghGet(path);if(!f)return def;let txt=decodeURIComponent(escape(atob(f.content.replace(/\n/g,''))));return JSON.parse(txt)}
function b64Unicode(str){return btoa(unescape(encodeURIComponent(str)))}
async function ghPutJson(path,obj,msg){let old=await ghGet(path);let body={message:msg||('Update '+path),content:b64Unicode(JSON.stringify(obj,null,2)),branch:state.settings.branch||'main'};if(old&&old.sha)body.sha=old.sha;let r=await fetch(ghApi(path),{method:'PUT',headers:githubHeaders(),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return await r.json()}
function rawUrl(path){return `${RAW}/${state.settings.owner}/${state.settings.repo}/${state.settings.branch||'main'}/${path}`}
function app(html){$('#app').innerHTML=html}
function guard(){loadSettings();if(!state.settings.token||!state.settings.owner||!state.settings.repo||!state.settings.tmdb){login();return false}return true}
function login(){app(`<div class="login"><div class="loginbox card"><div class="brand"><div class="logo">B</div>BIDAMAX ADMIN</div><p class="muted">GitHub Pages JSON Admin</p><div class="field"><label>GitHub Username / Owner</label><input id="owner" class="input" value="${state.settings.owner||''}"></div><div class="field"><label>Repository Name</label><input id="repo" class="input" value="${state.settings.repo||''}"></div><div class="field"><label>Branch</label><input id="branch" class="input" value="${state.settings.branch||'main'}"></div><div class="field"><label>GitHub Token</label><input id="token" class="input" type="password" value="${state.settings.token||''}"></div><div class="field"><label>TMDB API Key</label><input id="tmdb" class="input" type="password" value="${state.settings.tmdb||''}"></div><button class="btn red" onclick="doLogin()">Save Login</button><p class="muted small">Token needs repository contents read/write permission.</p></div></div>`)}
function doLogin(){saveSettings({owner:$('#owner').value.trim(),repo:$('#repo').value.trim(),branch:$('#branch').value.trim()||'main',token:$('#token').value.trim(),tmdb:$('#tmdb').value.trim()});dashboard()}
function shell(content,active='dash'){app(`<div class="wrap"><div class="top"><div class="brand"><div class="logo">B</div>BIDAMAX ADMIN</div><div class="nav"><button class="btn ${active==='dash'?'active':''}" onclick="dashboard()">Dashboard</button><button class="btn ${active==='add'?'active':''}" onclick="addSeries()">Add Series</button><button class="btn ${active==='manage'?'active':''}" onclick="manageSeries()">Manage</button><button class="btn" onclick="login()">Settings</button></div></div>${content}</div>`)}
async function loadSeries(){state.series=await ghGetJson('database/series.json',[]);return state.series}
async function dashboard(){if(!guard())return;try{await loadSeries();let total=state.series.length;let ep=0;let ss=0;state.series.forEach(x=>{ep+=Number(x.episode_count||x.NumberOfEpisodes||0);ss+=Number(x.season_count||x.NumberOfSeasons||0)});shell(`<div class="grid"><div class="card stat"><h2>${total}</h2><p>Total Series</p></div><div class="card stat"><h2>${ss}</h2><p>Total Seasons</p></div><div class="card stat"><h2>${ep}</h2><p>Total Episodes</p></div><div class="card stat"><h2>GitHub</h2><p>JSON Database</p></div></div><div class="card" style="margin-top:12px"><h3>Raw Links</h3><p class="muted small">series.json</p><input class="input" value="${rawUrl('database/series.json')}" readonly><p class="muted small">Structure: database/seasons/{tmdb_id}.json and database/episodes/{tmdb_id}.json</p></div><div class="card" style="margin-top:12px"><h3>Recently Added</h3><div class="list">${state.series.slice(-8).reverse().map(seriesRow).join('')||'<p class="muted">No series yet.</p>'}</div></div>`)}catch(e){toast(e.message)}}
function seriesRow(s){let id=s.id||s.tmdbID||s.tmdb_id;return `<div class="seriesItem"><img class="poster" src="${s.poster?IMG+s.poster:''}" onerror="this.style.visibility='hidden'"><div><b>${s.title||s.Title}</b><div class="muted small">ID: ${id} • ${s.year||s.Year||'n/a'} • ${s.episode_count||s.NumberOfEpisodes||0} eps</div><div>${(s.genres||s.Genres||[]).slice? (s.genres||s.Genres||[]).slice(0,3).map(g=>`<span class="pill">${g}</span>`).join('') : ''}</div></div><div class="actions"><button class="btn" onclick="episodesEditor('${id}')">Episodes</button><button class="btn" onclick="editSeries('${id}')">Edit</button></div></div>`}
function addSeries(){if(!guard())return;shell(`<div class="card"><h2>Add Series from TMDB</h2><div class="row"><div class="field"><label>TMDB ID</label><input id="tmdbid" class="input" placeholder="Example: 1396"></div><div class="field"><label>Search by Title</label><input id="q" class="input" placeholder="Example: Naruto"></div></div><div class="actions"><button class="btn red" onclick="fetchById()">Fetch by ID</button><button class="btn" onclick="searchTmdb()">Search Title</button></div></div><div id="results"></div>`, 'add')}
async function searchTmdb(){let q=$('#q').value.trim();if(!q)return toast('Enter title');let r=await fetch(`https://api.themoviedb.org/3/search/tv?api_key=${state.settings.tmdb}&query=${encodeURIComponent(q)}`);let j=await r.json();$('#results').innerHTML=`<div class="card" style="margin-top:12px"><h3>Results</h3><div class="list">${(j.results||[]).slice(0,12).map(x=>`<div class="seriesItem"><img class="poster" src="${x.poster_path?IMG+x.poster_path:''}"><div><b>${x.name}</b><div class="muted small">${x.first_air_date||''} • ID ${x.id}</div><p class="muted">${(x.overview||'').slice(0,120)}</p></div><button class="btn red" onclick="fetchById(${x.id})">Select</button></div>`).join('')||'<p>No result</p>'}</div></div>`}
async function fetchById(id){id=id||$('#tmdbid').value.trim();if(!id)return toast('Enter TMDB ID');try{let r=await fetch(`https://api.themoviedb.org/3/tv/${id}?api_key=${state.settings.tmdb}&append_to_response=images,credits,videos`);let j=await r.json();if(j.success===false)throw new Error('Series not found');let data=mapSeries(j);$('#results').innerHTML=previewSeries(data);window.__pendingSeries=data}catch(e){toast(e.message)}}
function mapSeries(j){let logo='n/a';let logos=(((j.images||{}).logos)||[]).filter(l=>l.iso_639_1==='en'&&l.file_path&&!l.file_path.includes('.svg'));if(logos[0])logo=logos[0].file_path;let tr='n/a';(((j.videos||{}).results)||[]).some(v=>{if(v.type==='Trailer'){tr=v.key;return true}});return {id:String(j.id),title:j.name||j.original_name||'n/a',poster:j.poster_path||'n/a',backdrop:j.backdrop_path||'n/a',logo,overview:j.overview||'n/a',genres:(j.genres||[]).map(g=>g.name),language:j.original_language||'n/a',vote:String(j.vote_average||'n/a'),year:(j.last_air_date||j.first_air_date||'n/a').slice(0,4),runtime:String(((j.episode_run_time||[])[0])||'n/a'),status:j.status||'n/a',season_count:j.number_of_seasons||0,episode_count:j.number_of_episodes||0,trailer:tr,adult:String(j.adult||false),seasons:(j.seasons||[]).filter(s=>s.season_number!==0).map(s=>({season:s.season_number,title:s.name||`Season ${s.season_number}`,episode_count:s.episode_count||0,overview:s.overview||'n/a',poster:s.poster_path||'n/a',air_date:s.air_date||'n/a'}))}}
function previewSeries(s){return `<div class="card" style="margin-top:12px"><div class="preview"><img src="${s.poster!=='n/a'?IMG+s.poster:''}"><div><h2>${s.title}</h2><p class="muted">${s.year} • ${s.season_count} seasons • ${s.episode_count} episodes</p><p>${s.overview}</p><div>${s.genres.map(g=>`<span class="pill">${g}</span>`).join('')}</div><br><button class="btn red" onclick="savePendingSeries()">Save + Generate Seasons/Episodes</button></div></div></div>`}
async function savePendingSeries(){let s=window.__pendingSeries;if(!s)return;try{await loadSeries();let idx=state.series.findIndex(x=>String(x.id||x.tmdbID)===String(s.id));let minimal={id:s.id,title:s.title,poster:s.poster,backdrop:s.backdrop,logo:s.logo,overview:s.overview,genres:s.genres,language:s.language,vote:s.vote,year:s.year,runtime:s.runtime,status:s.status,season_count:s.season_count,episode_count:s.episode_count,trailer:s.trailer,adult:s.adult};if(idx>=0)state.series[idx]=minimal;else state.series.push(minimal);await ghPutJson('database/series.json',state.series,'Update series.json');await ghPutJson(`database/seasons/${s.id}.json`,s.seasons,`Update seasons ${s.title}`);let eps=[];for(const sea of s.seasons){let r=await fetch(`https://api.themoviedb.org/3/tv/${s.id}/season/${sea.season}?api_key=${state.settings.tmdb}&language=en-US`);let j=await r.json();(j.episodes||[]).forEach(e=>eps.push({season:sea.season,episode:e.episode_number,title:e.name||`Episode ${e.episode_number}`,overview:e.overview||'n/a',poster:e.still_path||'n/a',air_date:e.air_date||'n/a',runtime:e.runtime||'',link:''}))}
await ghPutJson(`database/episodes/${s.id}.json`,eps,`Generate episodes ${s.title}`);toast('Saved to GitHub');manageSeries()}catch(e){toast(e.message)}}
async function manageSeries(){if(!guard())return;await loadSeries();shell(`<div class="card"><div class="searchbar"><input id="filter" class="input" placeholder="Search series..." oninput="renderManage()"><button class="btn red" onclick="addSeries()">Add</button></div><div id="manageList" class="list"></div></div>`, 'manage');renderManage()}
function renderManage(){let q=($('#filter')?.value||'').toLowerCase();let list=state.series.filter(s=>(s.title||'').toLowerCase().includes(q)||String(s.id).includes(q));$('#manageList').innerHTML=list.map(seriesRow).join('')||'<p class="muted">No series.</p>'}
async function editSeries(id){let s=(await loadSeries()).find(x=>String(x.id)===String(id));if(!s)return;window.__editId=id;shell(`<div class="card"><h2>Edit Series</h2><div class="row"><div class="field"><label>Title</label><input id="title" class="input" value="${esc(s.title)}"></div><div class="field"><label>Year</label><input id="year" class="input" value="${esc(s.year||'')}"></div></div><div class="field"><label>Overview</label><textarea id="overview" class="textarea">${esc(s.overview||'')}</textarea></div><div class="row"><div class="field"><label>Poster path</label><input id="poster" class="input" value="${esc(s.poster||'')}"></div><div class="field"><label>Backdrop path</label><input id="backdrop" class="input" value="${esc(s.backdrop||'')}"></div></div><div class="actions"><button class="btn red" onclick="saveEditSeries()">Save</button><button class="btn" onclick="manageSeries()">Cancel</button><button class="btn yellow" onclick="deleteSeries('${id}')">Delete</button></div></div>`)}
function esc(s){return String(s||'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
async function saveEditSeries(){let id=window.__editId;let idx=state.series.findIndex(x=>String(x.id)===String(id));state.series[idx].title=$('#title').value;state.series[idx].year=$('#year').value;state.series[idx].overview=$('#overview').value;state.series[idx].poster=$('#poster').value;state.series[idx].backdrop=$('#backdrop').value;await ghPutJson('database/series.json',state.series,'Edit series');toast('Saved');manageSeries()}
async function deleteSeries(id){if(!confirm('Delete from series.json only?'))return;state.series=state.series.filter(x=>String(x.id)!==String(id));await ghPutJson('database/series.json',state.series,'Delete series');toast('Deleted');manageSeries()}
async function episodesEditor(id){try{let eps=await ghGetJson(`database/episodes/${id}.json`,[]);let seasons=[...new Set(eps.map(e=>e.season))].sort((a,b)=>a-b);window.__eps={id,eps};shell(`<div class="card"><h2>Episodes Editor</h2><p class="muted">Series ID: ${id}</p><div class="tabs">${seasons.map(s=>`<button class="btn" onclick="renderEpisodes(${s})">Season ${s}</button>`).join('')}</div><div class="actions"><button class="btn red" onclick="saveEpisodes()">Save Episodes</button><button class="btn" onclick="bulkLinks()">Bulk Paste Links</button></div><div id="epList"></div></div>`,'manage');renderEpisodes(seasons[0]||1)}catch(e){toast(e.message)}}
function renderEpisodes(season){let eps=window.__eps.eps.filter(e=>Number(e.season)===Number(season));$('#epList').innerHTML=eps.map((e,i)=>{let idx=window.__eps.eps.indexOf(e);return `<div class="episode"><b>S${e.season} E${e.episode}</b><div><div class="field"><label>Title</label><input class="input" value="${esc(e.title)}" onchange="window.__eps.eps[${idx}].title=this.value"></div><div class="field"><label>Video Link</label><input class="input" value="${esc(e.link)}" onchange="window.__eps.eps[${idx}].link=this.value" placeholder="Paste video link"></div><details><summary class="muted">Overview / Poster</summary><textarea class="textarea" onchange="window.__eps.eps[${idx}].overview=this.value">${esc(e.overview)}</textarea><input class="input" value="${esc(e.poster)}" onchange="window.__eps.eps[${idx}].poster=this.value"></details></div></div>`}).join('')||'<p>No episodes.</p>'}
async function saveEpisodes(){await ghPutJson(`database/episodes/${window.__eps.id}.json`,window.__eps.eps,'Update episode links');toast('Episodes saved')}
function bulkLinks(){let season=prompt('Season number?','1');if(!season)return;let links=prompt('Paste links separated by newline or comma','');if(!links)return;let arr=links.split(/[\n,]+/).map(x=>x.trim()).filter(Boolean);let eps=window.__eps.eps.filter(e=>Number(e.season)===Number(season)).sort((a,b)=>a.episode-b.episode);arr.forEach((l,i)=>{if(eps[i])eps[i].link=l});renderEpisodes(season);toast('Links applied, click Save')}
loadSettings();guard()&&dashboard();
